### ISSUE TITLE
getVariables() method issue

### ISSUE THREAD

**Issue by mywhere** [vasrap/ZF2-Restful-Module-Skeleton#2]
Thanks for this great restful example. But it seems the module.php has some problem based on ZF2 beta 3 when request category.json and thumb.json, as for these two controllers, their getList is returned an array, but not ViewModel. $e->getResult()->getVariables() doesn't work.
So in my local, the fixture is:
Module.php (Line 53)
                        $vars = $e->getResult();
            if($vars instanceof \Zend\View\Model\ViewModel)
            {
                $vars = $e->getResult()->getVariables();
            }
            $postProcessor = $di->get($formatter . '-pp', array(
                'vars'     => $vars,
                'response' => $e->getResponse()
            ));

**Comment by vasrap** [comment]
Hi John, thanks for highlighting this. 

I verified the issue. Feel free to open a pull request with your fix.

Thanks again!
