### ISSUE TITLE
The requested URL could not be matched by routing

### ISSUE THREAD

**Issue by spinx** [vasrap/ZF2-Restful-Module-Skeleton#3]
Cloned latest ZF2, cloned this module to /modules/Main, added the module to application config. 

It's not working for me. Other modules work just fine.

**Comment by vasrap** [comment]
Spinx, what is not working for you exactly. Can you please provide steps to reproduce the problem?

Thanks

Vasilis

**Comment by spinx** [comment]
I can't get any REST routes of this module to work. 

If I add normal route to controller that extends ActionController in this module, it works.

**Comment by vasrap** [comment]
Hmm I will check if anything changed in any recent ZF2 commits. Thanks!

**Comment by vasrap** [comment]
Fixed (88a2be1)
