### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Serhioromano** [vasrap/ZF2-Restful-Module-Skeleton#4]
When I tryt o use your module in latest Zend Framework and Skeleton Application I get this error

 ![error](http://serhioromano.s3.amazonaws.com/public-screenshots/infojson.png)

**Comment by vasrap** [comment]
Thanks Sergey. I will have a look this weekend. Cheers.

**Comment by Serhioromano** [comment]
I have solved it. There was some error in description. You said just run /info.json but in fact I had to run  /rest/info.json
