### ISSUE TITLE
Question about posible reason not function

### ISSUE THREAD

**Issue by Serhioromano** [vasrap/ZF2-Restful-Module-Skeleton#5]
I changed standard skeleton structure. Now index.php is not in public directory. It is like this

```
config
data
module
|--Application
|--Main
`--other apps..
themes
|--desktop
|  `--default
`--mobile
   `--default
vendor
index.php
```

There are number of reasons why I did it and it is not an issue. But in this structure if I try /info.json gives apache 404 error. Not Zend Skeleton 404. In the issue I submitted previously the structure is standard.

So, do you know any reason why it may not work? Can index.php replacement to influence it?

Because Application module works ok and other modules seems to work too.

You know what I actually need is Zend restful **application** skeleton. not a simple module but  embedded it in to skeleton so the whole skeleton turn into resftul service.

**Comment by vasrap** [comment]
Please, pull and try again. Hopefully it is fixed now.

**Comment by vasrap** [comment]
Closing due to no reply.
