### ISSUE TITLE
unable to fetch or create an instance for info

### ISSUE THREAD

**Issue by austerus** [vasrap/ZF2-Restful-Module-Skeleton#7]
Hello,

I tried to add this module to the ZF2 Skeleton Application, using the latest pull from the zf2 repo (two days ago) but when I tried to access /info.json I got this error:

"Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for info

In addition, to make it work I had to change the ->headers() call in the JSON postprocessor to ->getHeaders() to match the current state of the Framework.

I am rather new at ZF2 so any suggestion/fix would be greatly appreciated as this skeleton module is the closest thing I came to seeing the RestfulController work.

Regards!

**Comment by vasrap** [comment]
Hi Andrei, 

Yeah at this point ZF2 is changing rapidly. Let me take a look and I will commit any fixes.

Thanks!

-- V

**Comment by vasrap** [comment]
Alright, this should be fixed now. Please, confirm and close issue.

**Comment by vasrap** [comment]
Closing due to no answer in 30 days.
